window.languages = [
  ['zh-Hans', '简体中文', {
    'loading': '少女祈祷中…',
    'tip-1': '鸣 谢 榆 木 华',
    'tip-2': '没有头绪？先随便碰一碰，再靠乐理素养蒙混过关吧！',
    'tip-3': '重要的曲子，不能忘记的曲子，不想忘记的曲子。你，是谁？😭',
    'tip-4': '榆 木 华 在 看 着 你',
    'tip-5': '善用THBWiki，鼓励现场扒谱，打过STG的同学也许更吃香',
    'rules': 'Medle 游戏规则',
    'rule-01': '猜出旋律中的每个音符。',
    'rule-02': '玩家不必具备音乐知识，Medle 可以是纯粹的数字游戏。',
    'rule-03': '音符用 1 至 7 的数字表示。每次猜测后，将针对每个音符给出提示。',
    'rule-04': '猜出旋律中的每个音符。',
    'rule-05': '玩家不必具备音乐知识，Medle 可以是纯粹的数字游戏。',
    'rule-06': '音符用 1 至 7 的数字表示。每次猜测后，将针对每个音符给出提示。',
    'rule-11': '音符“2”处于谜底中的正确位置。',
    'rule-12': '音符“3”出现在谜底中，但并不在猜测的位置上。',
    'rule-21': '若同一音符出现多次，则也会提示多次。',
    'rule-31': '一个音符“1”在正确的位置；除此之外，谜底中还有两个“1”，但都不在猜测为“1”的位置上。',
    'rule-41': '游戏中出现的其余记号只影响发出的声音，不影响游戏规则。',
    'rule-51': '除数字、颜色外的记号均不影响游戏。其含义留给有兴趣的玩家自行探索。',
    'rule-61': '一共有 5 到 6 次机会。游戏愉快~',
    'daily-update': '每天 00:00 更新谜题（UTC 16:00），记得回来呀！',
    'links': '也试试其他版本的 Medle ？ ',
    'link-1': 'Medle',
    'link-2': 'VOCALO Medle',
    'link-3': 'A-SOUL Medle',
    'bonus': '显示隐藏关',
    'guide-today-1-pfx': '正在访问的是一份过往的谜题 ',
    'guide-today-1-sfx': '。',
    'guide-today-2-pfx': '希望继续游玩，还是前往今天的每日谜题 ',
    'guide-today-2-sfx': ' 呢？',
    'btn-confirm': '确认',
    'btn-share': '分享',
    'btn-shared': '已复制到剪贴板',
    'curator': '选题',
    'curator-today': '今日选题',
    'archive': '过往谜题',
    'special': '隐藏谜题',
    'opt-title': '选项',
    'opt-sfx': '播放声音',
    'opt-metronome': '节拍提示',
    'opt-dark': '深色主题',
    'opt-flow': '显示瀑布',
    'opt-high-con': '清晰显示',
    'opt-nota': '音符记号',
    'opt-nota-num': '数字',
    'opt-nota-solf': '唱名',
    'opt-nota-alpha': '字母',
    'opt-nota-roman': '罗马',
    'opt-nota-aikin': '图形',
    'opt-nota-blank': '空',
    'opt-lang': '界面语言',
    'opt-source': '程序源码',
    'opt-dist': '依照木兰公共许可证分发',
    'opt-stat': '统计模式',
    'opt-stat-1': '总和',
    'opt-stat-2': '每日',
    'opt-stat-3': '隐藏',
    'opt-stat-tip': '注意：在 #005 之前的谜题信息将不会自动加入。请访问这些谜题以让程序加入这些数据。',
    'next-puzzle': '这一天的下一道谜题：',
    'visitors': '人尝试了这个谜题。',
    'guess-and-count': '猜测次数 / 统计',
    'fail': '失败',
    'step-1': '1 次猜中',
    'step-2': '2 次猜中',
    'step-3': '3 次猜中',
    'step-4': '4 次猜中',
    'step-5': '5 次猜中',
    'step-6': '6 次猜中',
    'step-7': '7 次猜中',
    'step-8': '8 次猜中',
    'step-9': '9 次猜中',
    'step-10': '10 次猜中',
    'server': '服务器开始运作于',
    'opt-offset': "音乐延时",
    'adjust': '校准',
    'pop-faster': '音符前移',
    'music-faster': "音乐前移",
    'cick-on-high-pitch': "在高音的时候点击屏幕或者按下按键",
    'total-puzzles': '总共完成猜谜',
    'accuracy': '成功率',
    'average-steps': '平均步数',
    'total-pass-person': '完成猜谜人数',
    'hidden': 'Bonus'
  }],
  ['en', 'English', {
    'loading': 'Loading…',
    'tip-1': 'Try turning on sound!',
    'tip-2': 'Press the bubbles to replay the sounds',
    'tip-3': 'Dark theme is recommended at night',
    'tip-4': 'The metronome can be brought in through the options page',
    'tip-5': 'Ever played the game with letters or shapes?',
    'rules': 'Medle Rules',
    'rule-01': 'Guess the notes in the melody.',
    'rule-02': 'No musical knowledge is required; Medle is essentially a game of numbers.',
    'rule-03': 'Notes are denoted by digits from 1 through 7. After every guess, hints will be given for each note.',
    'rule-04': 'Guess the notes in the melody.',
    'rule-05': 'No musical knowledge is required; Medle is essentially a game of numbers.',
    'rule-06': 'Notes are denoted by digits from 1 through 7. After every guess, hints will be given for each note.',
    'rule-11': 'The note “2” is in the correct place.',
    'rule-12': 'The note “3” is in the solution, but in the wrong place.',
    'rule-21': 'If a note appears more than once, more hints will be given.',
    'rule-31': 'One of the notes “1” is correct; there are additionally two such notes in the solution, but not in places guessed as “1”.',
    'rule-41': 'All other symbols affect only the sound and not the rules.',
    'rule-51': 'The game is not affected by symbols other than numbers and tints, whose meanings are left for exploration to the curious player.',
    'rule-61': 'There are 5 or 6 chances. Have fun!',
    'daily-update': 'Some new puzzles are published every day at 16:00 UTC. It will be delighting to see you come back!',
    'links': 'Try other versions of Medle? ',
    'link-1': ' Medle',
    'link-2': ' VOCALO Medle',
    'bonus': 'Show bonus levels',
    'guide-today-1-pfx': 'You are currently visiting a past puzzle ',
    'guide-today-1-sfx': '.',
    'guide-today-2-pfx': 'Would you like to continue playing, or visit today\'s daily puzzle ',
    'guide-today-2-sfx': '?',
    'btn-confirm': 'Confirm',
    'btn-share': 'Share',
    'btn-shared': 'Copied to clipboard',
    'curator': 'Curator',
    'curator-today': 'Today\'s curator',
    'archive': 'Puzzle Archive',
    'special': 'Special Puzzles',
    'opt-title': 'Options',
    'opt-sfx': 'Play sound',
    'opt-metronome': 'Metronome',
    'opt-dark': 'Dark theme',
    'opt-flow': 'Show waterfall flow',
    'opt-high-con': 'Sharp display',
    'opt-nota': 'Notation',
    'opt-nota-num': 'Numeral',
    'opt-nota-solf': 'Solfege',
    'opt-nota-alpha': 'Alphabet',
    'opt-nota-roman': 'Roman',
    'opt-nota-aikin': 'Shape',
    'opt-nota-blank': 'Blank',
    'opt-lang': 'Language',
    'opt-source': 'Program source',
    'opt-dist': ' distributed under the Mulan Public License',
    'opt-stat': 'Statistic mode',
    'opt-stat-1': 'Overall',
    'opt-stat-2': 'Daily',
    'opt-stat-3': 'Bonus',
    'opt-stat-tip': 'Note: datas before puzzle #005 won\'t automately be added. Please visit the puzzles in order to add them.',
    'next-puzzle': 'Next puzzle of this day:',
    'visitors': 'people tried this puzzle.',
    'guess-and-count': 'Guesses / Count',
    'fail': 'Fail',
    'step-1': '1 Try',
    'step-2': '2 Tries',
    'step-3': '3 Tries',
    'step-4': '4 Tries',
    'step-5': '5 Tries',
    'step-6': '6 Tries',
    'step-7': '7 Tries',
    'step-8': '8 Tries',
    'step-9': '9 Tries',
    'step-10': '10 Tries',
    'server': 'Server started at',
    'opt-offset': 'Music offset',
    'adjust': 'Adjust',
    'pop-faster': 'Move pop forward',
    'music-faster': "Move music forward",
    'cick-on-high-pitch': "Click the screen or press a key when you hear a high pitch",
    'total-puzzles': 'Finished puzzles',
    'accuracy': 'Accuracy',
    'average-steps': 'Average Step',
    'total-pass-person': 'Passed people count',
    'hidden': 'Bonus'
  }],
];
